name: Junit test and Checkstyle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Get Junit Launcher (this includes the JUnit Libs)
      run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.1/junit-platform-console-standalone-1.8.1.jar
      # TODO: separate tests from project
    - name: Build Code for testing
      # TODO/Note: update for number of nested folders at end of this command
      run: javac -cp junit-platform-console-standalone-1.8.1.jar -d build/classes/ci src/*/java/*/*/*/*.java
    - name: Run junit test
      run: java -jar junit-platform-console-standalone-1.8.1.jar --reports-dir=build/test-results/test -cp build/classes/ci --scan-classpath

    # post the junit test results
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-junit-jupiter.xml'
    # run and post the checkstyle test
    - name: Get noTest.xml
      run: wget noTest.xml
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      if: always() # always run even if the previous step fails
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-check'
        checkstyle_config: https://github.com/tztz8/HelloGradle/raw/master/ewu-cscd212-noTest.xml
    # Helps with debugging
    - name: Show File Tree
      if: always()
      run: tree